# Generated by Django 3.0 on 2021-07-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('flat', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('net_income', models.IntegerField()),
            ],
        ),
    ]
